// Code generated by "stringer -type=Tier"; DO NOT EDIT.

package patreon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Premium-0]
	_ = x[Whitelabel-1]
}

const _Tier_name = "PremiumWhitelabel"

var _Tier_index = [...]uint8{0, 7, 17}

func (i Tier) String() string {
	if i < 0 || i >= Tier(len(_Tier_index)-1) {
		return "Tier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tier_name[_Tier_index[i]:_Tier_index[i+1]]
}
